version: '3.8'

services:
  florent-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
      # Optionally mount local data directories if you want to use file path references
      - ./src/data:/app/src/data # for local test
    restart: always
