services:
  bge-m3:
    image: mdelapenya/bge-m3:0.3.13-567m
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:11434/" ]
      interval: 30s
      timeout: 10s
      retries: 3
